name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_intl: ^0.0.1
  
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
